apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: {{ .Values.app.contextPath }}
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ingressClassName: {{ .Values.ingress.class }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.app.contextPath }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ .Chart.Name }}
                port:
                  number: {{ .Values.ports.main.number }}